# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3359f9d4bf2ec792a2665e0ccf4b93f"
web_directories = [ "web" ]
name = "Optimo VTS Dev"
application_url = "https://optimo-virtual-try-on-rose.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "shop/update", "app_subscriptions/update" ]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_app_proxy,write_products,write_script_tags"

[auth]
redirect_urls = [ "https://optimo-virtual-try-on.vercel.app/api/auth/callback" ]

[app_proxy]
url = "https://optimo-virtual-try-on.vercel.app/widget-proxy"
subpath = "optimo-vts"
prefix = "apps"
