# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b04a4ca34b41318b2c1a92fb5f427563"
web_directories = [ "web" ]
name = "Optimo-Virtual Try-On"
application_url = "https://optimo-virtual-try-on.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "shop/update", "app/uninstalled", "app_subscriptions/update" ]
  uri = "/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://optimo-virtual-try-on.vercel.app/api/auth/callback" ]
