"""Initial database schema

Revision ID: 7513a4ced961
Revises: 
Create Date: 2026-02-09 15:58:23.341100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7513a4ced961'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_deletion_queue',
    sa.Column('deletion_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('deletion_id')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('shopify_domain', sa.String(length=255), nullable=False),
    sa.Column('shopify_access_token', sa.Text(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('script_tag_id', sa.String(length=50), nullable=True),
    sa.Column('installation_status', sa.String(length=20), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(), nullable=True),
    sa.Column('reinstalled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_stores_shopify_domain'), 'stores', ['shopify_domain'], unique=True)
    op.create_table('analytics_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_analytics_store_time', 'analytics_events', ['store_id', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_size_chart', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('store_id', 'shopify_product_id', name='uix_store_product')
    )
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.create_index('idx_products_store', 'products', ['store_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('measurement_id', sa.UUID(), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_sessions_expires', 'sessions', ['expires_at'], unique=False)
    op.create_table('size_charts',
    sa.Column('size_chart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_name', sa.String(length=20), nullable=False),
    sa.Column('size_system', sa.String(length=20), nullable=True),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('size_chart_id')
    )
    op.create_index('idx_size_charts_product', 'size_charts', ['product_id'], unique=False)
    op.create_table('user_measurements',
    sa.Column('measurement_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('body_type', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_index('idx_measurements_session', 'user_measurements', ['session_id'], unique=False)
    op.create_table('size_recommendations',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('measurement_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('recommended_size', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['user_measurements.measurement_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('try_ons',
    sa.Column('try_on_id', sa.UUID(), nullable=False),
    sa.Column('measurement_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('size_name', sa.String(length=20), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('result_cache_key', sa.String(length=200), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['user_measurements.measurement_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('try_on_id')
    )
    op.create_index('idx_try_ons_measurement', 'try_ons', ['measurement_id'], unique=False)
    op.create_index('idx_try_ons_status', 'try_ons', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_try_ons_status', table_name='try_ons')
    op.drop_index('idx_try_ons_measurement', table_name='try_ons')
    op.drop_table('try_ons')
    op.drop_table('size_recommendations')
    op.drop_index('idx_measurements_session', table_name='user_measurements')
    op.drop_table('user_measurements')
    op.drop_index('idx_size_charts_product', table_name='size_charts')
    op.drop_table('size_charts')
    op.drop_index('idx_sessions_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_products_store', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_analytics_store_time', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_stores_shopify_domain'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('data_deletion_queue')
    # ### end Alembic commands ###
